### ISSUE TITLE
Apps.config files does not contain all the dockerapp applications available in DockerHub

### ISSUE THREAD

**Issue by ghost** [admpresales/nimbusapp#9]
This file should include all the available applications
ALM
AOS
Autopass
DA
Devops
Intellij
MC
Octane

**Comment by jhrabi** [comment]
The apps.config file is meant to be a template, not a list of all available products. I can write up a usage document for the apps.config file, but I'm not intending to re-release the application everytime we update a new version of a container, or if we release a new container, because the application will still work as is.

**Comment by panama69** [comment]
@jeff-kingston when the next version is released, we will plan to have a broader listing along with the latest versions at that time.  but i agree with @jhrabi that the app.config file will not be updated every time a new image is available.  that will be expected for the individuals to update as and when they see fit.
